In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


#creating arrays:-

In [4]:
list1=[1,2,3]
print(list1)

[1, 2, 3]


In [16]:
array_list1=np.array(list1)
print(array_list1)

[1 2 3]


In [17]:
list1=[1,2,3]
list2=[4,5,6]
array_list1_2=np.array([list1,list2])
print(array_list1_2)

[[1 2 3]
 [4 5 6]]


In [18]:
print(array_list1_2.ndim)

2


In [19]:
#Initializations:-


#**Arrays and Slicing:-**

In [20]:
a=np.array([1,3,5,7,9])
print(a)
print(a[0:3]) #first three elements
print(a[-3:])#last three elements

[1 3 5 7 9]
[1 3 5]
[5 7 9]


In [21]:
#2D arrays:-
a2=np.array([[1,2,3],[4,5,6]])
print(a2)


[[1 2 3]
 [4 5 6]]


In [22]:
print(a2[1][0])

4


In [23]:
print(a2[1])
print(a2[1:])

[4 5 6]
[[4 5 6]]


In [24]:
print(a2[:,1])
print(a2[:,2])

#2D: [rows,olumns]
#3D: [layers/height,rows, columns]

[2 5]
[3 6]


In [25]:
#3D array:-
a3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(a3[0])
print(a3[1])
print(a3[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [27]:
print(a3[0][2])
print(a3[2][2])

3
9


In [28]:
print(a3[:, 0]) #first column

[1 4 7]


In [29]:
print(a3[::2,0]) #in first column by step 2
print("     ")
print(a3[::,1:2]) # before , it means it will take all rows and after , it takes colums (slicing on columns)
print("     ")
print(a3[2::,1:2]) # starts from

[1 7]
     
[[2]
 [5]
 [8]]
     
[[8]]


In [30]:
#asarray() with nditer():-
a=[10,20,30]
b=np.asarray(a,dtype=float)
print(b)


[10. 20. 30.]


In [36]:
a=[[10,20],[30,40]]
b=np.asarray(a,order="C")#it means row wise execution
c=np.asarray(a,order="F")#it means column-wise execution
print(b)
print(c)# here these executes normal but when we appy nditer() we will see row wise and column wise
print("with nditer():-")
print("row wise:")
for i in np.nditer(b):
    print(i)
print("column wise")
for j in np.nditer(c):
    print(j)

[[10 20]
 [30 40]]
[[10 20]
 [30 40]]
with nditer():-
row wise:
10
20
30
40
column wise
10
30
20
40


**#methods can use to create arrays:-**

In [44]:
#methods can use to create arrays:-
#frombuffer():
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1") #in the string format


array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o', b' ',
       b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

In [45]:
np.frombuffer(a,dtype="S1",count=10)# no.of char to be displayed


array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o'],
      dtype='|S1')

In [46]:
np.frombuffer(a,dtype="S1",count=2,offset=9)#from which char index it should start


array([b'o', b' '], dtype='|S1')

In [42]:
#fromiter():
a=[10,30,40,50]
np.fromiter(a,dtype="S1",count=3)

array([b'1', b'3', b'4'], dtype='|S1')

**#initializing the array or creating:-**

In [53]:
#zeros array:-
a=np.zeros(3)
print(a)
x=np.zeros([2,3])#two dimensional
print(x)
y=np.zeros([2,3,3])#three dimen
print(y)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [52]:
#np.full():-it takes dimension and which value to be filled:-
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [57]:
#random numbers:-
a=np.random.rand(3)
print(a)
b=np.random.rand(2,3)
print(b)

[0.30551187 0.00752762 0.07622561]
[[0.36674398 0.317385   0.88129311]
 [0.66895746 0.94477459 0.36951469]]


In [59]:
#ones array
x=np.ones(5)
print(x)
y=np.ones([2,3])
print(y)

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [61]:
#diagnol ones(identity matrix)
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [64]:
#range:-
a=np.arange(10,20,1)
print(a)
b=np.arange(0,100,20,dtype=float)
print(b)

[10 11 12 13 14 15 16 17 18 19]
[ 0. 20. 40. 60. 80.]


In [68]:
#linspace:-
a=np.linspace(10,100,10)
print(a)
b=np.linspace(10,100,10,endpoint=False)
print(b)
c=np.linspace(10,100,10,endpoint=False,retstep=True)#retstep helps to know difference
print(c)
d=np.linspace(10,100,10,endpoint=False,retstep=True,dtype=int)
print(d)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[10. 19. 28. 37. 46. 55. 64. 73. 82. 91.]
(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)
(array([10, 19, 28, 37, 46, 55, 64, 73, 82, 91]), 9.0)


In [69]:
#logspace:-
np.logspace(1,10,10)


array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

**Array Reshaping and Flattening**

In [17]:
#Array Reshaping and Flattening
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [19]:
reshaped=arr.reshape((6,1))
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [21]:
reshaped2=arr.reshape((2,3))
print(reshaped2)

[[1 2 3]
 [4 5 6]]


In [22]:
print(reshaped2.flatten())

[1 2 3 4 5 6]


**#OPERATIONS OF ARRAY**

**#Array Stacking and Spitting**

In [26]:
#Array Stacking and Spitting
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack((a,b))) # vertical stacking :-row wise
print(" ")
print(np.hstack((a,b))) # horizontal stacking :-column wise

[[1 2 3]
 [4 5 6]]
 
[1 2 3 4 5 6]


In [28]:
c=np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [31]:
split=np.hsplit(c,3)

for s in split:
    print(s)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [33]:
split=np.vsplit(c,2)

for s in split:
    print(s)

[[1 2 3]]
[[4 5 6]]


In [35]:
# Mathematical Operations on Array
a=np.array([10,20,40,-30])
print(a)
print(a+10)
print(a-30)
print(a*2)
print(a/10)

[ 10  20  40 -30]
[ 20  30  50 -20]
[-20 -10  10 -60]
[ 20  40  80 -60]
[ 1.  2.  4. -3.]


In [36]:
# Mathematical Operations on Multiple Arrays:-
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [41]:
print("addition:",np.add(a,b))
print("subtract:",np.subtract(a,b))
print("multiplication:",np.multiply(a,b))
print("division:",np.divide(a,b))
print("dot product:",np.dot(a,b)) #dot product

addition: [5 7 9]
subtract: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]
dot product: 32


In [44]:
t=np.array([[1,2,3],[4,5,6]])
print(t)
print(" ")
print(t.T)

[[1 2 3]
 [4 5 6]]
 
[[1 4]
 [2 5]
 [3 6]]


In [45]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [46]:
print(np.sum(a))

21


In [47]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

3.5
3.5
1.707825127659933
1
6


In [49]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
print(a==b) #comparing each element
print(np.array_equal(a,b)) #comparing complete array

[1 2 3]
[4 5 6]
[False False False]
False


In [52]:
#BroadCasting:-(that allows arithmetic operations to be performed on arrays of different shapes and size)
a=np.array([1,2,3,4])
b=np.array([5])
print(a+b)

[6 7 8 9]


In [51]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([10,20,30])
print(c+d)

[[11 22 33]
 [14 25 36]]


In [54]:
#Handling with nan
data=np.array([1,2,np.nan,4,np.inf])
print(data)

[ 1.  2. nan  4. inf]


In [56]:
print(np.nan_to_num(data))

[1.00000000e+000 2.00000000e+000 0.00000000e+000 4.00000000e+000
 1.79769313e+308]


In [57]:
#save and load arrays:-
arr=np.array([1,0,0,8])
print(arr)
np.save('my_array.npy',arr)

[1 0 0 8]


In [58]:
loaded_arr=np.load('my_array.npy')
print(loaded_arr)

[1 0 0 8]


**#ARRAYS OPERATIONS:-**

In [6]:
#copy():- creates a new array
a=np.array([1,2,3])
b=a.copy()
print(b)
b[0]=90
print(b)

[1 2 3]
[90  2  3]


In [8]:
#view():- shares same data
a=np.array([1,2,3])
b=a.view()
b[0]=25
print(a)
print(b)

[25  2  3]
[25  2  3]


In [11]:
#sort():-
a=np.array([1,5,4,3])
print(np.sort(a))


[1 3 4 5]


In [12]:
#reshape():-
a=np.array([1,2,3,5])
print(a.reshape(2,2))

[[1 2]
 [3 5]]


In [13]:
#append():-
a=np.array([1,2,3])
print(np.append(a,5))

[1 2 3 5]


In [14]:
#insert():-
a=np.array([10,20,30])
print(np.insert(a,1,99))

[10 99 20 30]


In [16]:
#delete():-
a=np.array([1,2,3,4])
print(np.delete(a,2))

[1 2 4]


In [17]:
#concatenate():-
a=np.array([1,2])
b=np.array([9,10])
np.concatenate((a,b))

array([ 1,  2,  9, 10])

In [22]:
#vstack():-(Vertical Stack):-or stack()
a=np.array([11,12])
b=np.array([13,14])
print(np.vstack((a,b)))
print(np.stack((a,b)))

[[11 12]
 [13 14]]
[[11 12]
 [13 14]]


In [21]:
#hstack():-(Horizontal Stack):-
np.hstack((a,b))

array([11, 12, 13, 14])

In [23]:
#dstack():-(Depth Stack):-
np.dstack((a,b))

array([[[11, 13],
        [12, 14]]])

In [26]:
#split():-
a=np.array([1,2,3,4])
print(np.split(a,2))

[array([1, 2]), array([3, 4])]


In [45]:
#where():-
a=np.array([1,2,3,4])
print(np.where(a>2)) #we get indexs
print(np.where(a>2,"yes","no"))

(array([2, 3], dtype=int64),)
['no' 'no' 'yes' 'yes']


In [31]:
#searchsorted():-
a=np.array([1,3,5,7])
np.searchsorted(a,4) #it means 4 should be inserted at index 2 to keep sorted array

2

**#Array Properties:-**

In [33]:
x=np.array([[11,12,13],[19,20,21]])
print(x)
print(x.ndim)  #no.of dimensions
print(x.shape) #structure of array(row,columns)
print(x.size)  #total no of elements
print(x.dtype)  #data type of elements

[[11 12 13]
 [19 20 21]]
2
(2, 3)
6
int32


**#basic functions:-**

In [42]:
a=np.array([10,20,5,30])
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.sort(a))
#2D-array:-
b=np.array([[1,2,3],[4,5,6]])
print(np.sum(b,axis=0))
print(np.mean(b,axis=1))

65
16.25
30
5
[ 5 10 20 30]
[5 7 9]
[2. 5.]


In [43]:
#Boolean Masks:-
a=np.array([10,20,30,40,50])
mask=a>25
mask

array([False, False,  True,  True,  True])

In [44]:
#Indexing:-
a[[0,2,4]]

array([10, 30, 50])

**#AXIS Concept:-**

In [46]:
#axis:-gives direction that should work
#axis=0 :-down the rows means column wise
#axis=1  :-across the columns means row wise


**#Random module:-**

In [51]:
#rand()-random floats(0-1)
print(np.random.rand(3))

#randn()-normal distribution
print(np.random.randn(3))

#randint():-
print(np.random.randint(1,10,size=5))

#choice():-
np.random.choice([10,20,30],size=5)

[0.8623699  0.84058967 0.41387783]
[-0.86869218  1.58447755  0.76496385]
[1 8 2 4 6]


array([20, 20, 20, 20, 20])

**#Stastical functions:-**

In [53]:
a=np.array([10,20,30,40])
b=np.array([50,60,70,80])
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.percentile(a,75))
print(np.corrcoef(a,b))


25.0
11.180339887498949
125.0
32.5
[[1. 1.]
 [1. 1.]]
